application:
  name: hello-client

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
    fetchRegistry: true
    instance:
      preferIpAddress: true